name: Run Gosec

permissions:
  contents: read

on:
    workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run Gosec Security Scanner
        uses: securego/gosec@39e44777884117b67b8fd57dd75bb62c96ca92b7
        with:
          args: -exclude=G103,G115 ./...
